<a href="https://colab.research.google.com/github/daNizaparedesdenis-arch/ChallengeTelecomXprimeraparte/blob/main/telecomx_latam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#📌 Extracción

In [1]:
import pandas as pd
datos_telecomX = pd.read_json("TelecomX_Data.json")

In [2]:
datos_telecomX.head(5)

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

In [3]:
datos_telecomX.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

#🔧 Transformación

In [4]:
telecomX_customer_df = pd.json_normalize(datos_telecomX["customer"])
telecomX_phone_df = pd.json_normalize(datos_telecomX["phone"])
telecomX_internet_df = pd.json_normalize(datos_telecomX["internet"])
telecomX_account_df = pd.json_normalize(datos_telecomX["account"])

datos_telecomX_final = pd.concat([datos_telecomX.drop(columns=['customer','phone', 'internet', 'account']),
                                 telecomX_customer_df,
                                 telecomX_phone_df,
                                 telecomX_internet_df,
                                 telecomX_account_df],
                                axis=1)

In [5]:
datos_telecomX_final.head(5)

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [6]:
datos_telecomX_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

###Eliminación columnas no necesarias

In [7]:
datos_telecomX_depurada = datos_telecomX_final.drop(columns=['PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling'])
datos_telecomX_depurada.head(5)

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,Contract,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,One year,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Month-to-month,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Month-to-month,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Month-to-month,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Month-to-month,Mailed check,83.9,267.4

###Busqueda de datos ausentes

In [32]:
col = "Charges.Total"
s = datos_telecomX_depurada[col].astype("string")
mask = s.isna() | s.str.strip().eq("")
datos_telecomX_depurada[mask]

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,Contract,PaymentMethod,Charges.Monthly,Charges.Total
975,1371-DWPAZ,0,Female,0,Yes,Yes,0,Two year,Credit card (automatic),56.05,
1775,2520-SGTTA,0,Female,0,Yes,Yes,0,Two year,Mailed check,20.00,
1955,2775-SEFEE,0,Male,0,No,Yes,0,Two year,Bank transfer (automatic),61.90,
2075,2923-ARZLG,0,Male,0,Yes,Yes,0,One year,Mailed check,19.70,
2232,3115-CZMZD,0,Male,0,No,Yes,0,Two year,Mailed check,20.25,
2308,3213-VVOLG,0,Male,0,Yes,Yes,0,Two year,Mailed check,25.35,
2930,4075-WKNIU,0,Female,0,Yes,Yes,0,Two year,Mailed check,73.35,
3134,4367-NUYAO,0,Male,0,Yes,Yes,0,Two year,Mailed check,25.75,
3203,4472-LVYGI,0,Female,0,Yes,Yes,0,Two year,Bank transfer (automatic),52.55,
4169,5709-LVOEQ,0,Female,0,Yes,Yes,0,Two year,Mailed check,80.85,
5599,7644-OMVMY,0,Male,0,Yes,Yes,0,Two year,Mailed check,19.85,

In [35]:
import numpy as np

col = "Charges.Total"
s = datos_telecomX_depurada[col].astype("string")
mask = s.isna() | s.str.strip().eq("")
datos_telecomX_depurada.loc[mask, col] = 0

In [36]:
col = "Charges.Total"
s = datos_telecomX_depurada[col].astype("string")
mask = s.isna() | s.str.strip().eq("")
datos_telecomX_depurada[mask]

Empty DataFrame
Columns: [customerID, Churn, gender, SeniorCitizen, Partner, Dependents, tenure, Contract, PaymentMethod, Charges.Monthly, Charges.Total]
Index: []

###Datos duplicados

In [14]:
datos_telecomX_depurada.duplicated().sum()
datos_telecomX_depurada[datos_telecomX_depurada.duplicated()]

Empty DataFrame
Columns: [customerID, Churn, gender, SeniorCitizen, Partner, Dependents, tenure, Contract, PaymentMethod, Charges.Monthly, Charges.Total]
Index: []

In [15]:
datos_telecomX_depurada[datos_telecomX_depurada.duplicated(keep=False)].sort_values(by=datos_telecomX_depurada.columns.tolist())

Empty DataFrame
Columns: [customerID, Churn, gender, SeniorCitizen, Partner, Dependents, tenure, Contract, PaymentMethod, Charges.Monthly, Charges.Total]
Index: []

###Errores de formato

In [16]:
datos_telecomX_depurada.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customerID       7267 non-null   object
 1   Churn            7267 non-null   object
 2   gender           7267 non-null   object
 3   SeniorCitizen    7267 non-null   int64
 4   Partner          7267 non-null   object
 5   Dependents       7267 non-null   object
 6   tenure           7267 non-null   int64
 7   Contract         7267 non-null   object
 8   PaymentMethod    7267 non-null   object
 9   Charges.Monthly  7267 non-null   float64
 10  Charges.Total    7267 non-null   object
dtypes: float64(1), int64(2), object(8)
memory usage: 624.6+ KB

#📊 Carga y análisis

#📄Informe final